version: '3.8'
services:
  propops-server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  propops-client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - propops-server